name: happenin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  video_player: ^2.8.3
  image_picker: ^0.8.7+5
  carousel_slider: ^5.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/static_loading_page.png
    - assets/images/white_logo.png
    - assets/images/black.png
    - assets/videos/splash_screen.mp4
    - assets/images/google_logo.png
    - assets/images/location_pin.png
    - assets/images/profile_placeholder.png
    - assets/images/activities.png
    - assets/images/dining.png
    - assets/images/events.png
    - assets/images/for_you.png
    - assets/images/movies.png
    - assets/images/slide1.png
    - assets/images/slide2.png
    - assets/images/slide3.png
    - assets/images/spotlight1.png
    - assets/images/spotlight2.png
    - assets/images/spotlight3.png
    - assets/images/ai_assistant_logo.png
    - assets/images/buddy1.png
    - assets/images/buddy2.png
    - assets/images/buddy3.png
    - assets/images/buddy4.png
    - assets/images/groupchat.png
    - assets/videos/story1.mp4
    - assets/videos/story2.mp4
    - assets/videos/story3.mp4
    - assets/images/founder1.png
    - assets/images/founder2.png
    - assets/images/founder3.png

flutter_native_splash:
  android: true
  ios: true
  web: false

  background_image: assets/images/static_loading_page.png
  image: null
  android_gravity: center
  ios_content_mode: center

  android_12:
    color: "#000000"
    image: assets/images/black.png
