name: happenin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  video_player: ^2.8.3
  image_picker: ^0.8.7+5
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.10.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "adaptive"
  ios: true
  image_path_android: "assets/images/happenin_logo.png"
  adaptive_icon_background: "#2E0B5C" # solid purple background
  image_path_ios: "assets/images/happenin_logo.png" # your iOS logo

flutter:
  uses-material-design: true

  assets:
    - assets/images/static_loading_page.png
    - assets/images/white_logo.png
    - assets/images/black.png
    - assets/videos/splash_screen.mp4
    - assets/images/location_pin.png
    - assets/images/profile_placeholder.png
    - assets/images/logos/
    - assets/images/carousel_images/
    - assets/images/spotlight1.png
    - assets/images/spotlight2.png
    - assets/images/spotlight3.png
    - assets/images/buddy1.png
    - assets/images/buddy2.png
    - assets/images/buddy3.png
    - assets/images/buddy4.png
    - assets/images/groupchat.png
    - assets/videos/
    - assets/images/founders/
    - assets/images/purple_location_pin.png
    - assets/images/activities/
    - assets/images/dining/
    - assets/images/events/
    - assets/images/movies/

flutter_native_splash:
  android: true
  ios: true
  web: false

  background_image: assets/images/static_loading_page.png
  image: null
  android_gravity: center
  ios_content_mode: center

  android_12:
    color: "#000000"
    image: assets/images/black.png
